export const ROUTES = Object.freeze({
  home: "/",
  auth: {
    login: "/login",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    emailVerification: "/email-verification",
  },
  public: {
    employerLanding: "/for-employers",
    companyInvitation: (token = ":token") => `/company-invitations/${token}`,
  },
  admin: {
    root: "/admin",
    users: "/admin/all-users",
    userDetails: (id: string | number) => `/admin/all-users/${id}`,
    candidates: "/admin/candidates",
    employers: "/admin/employers",
    companies: "/admin/companies",
    companyDetails: (id: string | number) => `/admin/companies/${id}`,
    jobs: "/admin/jobs",
    jobDetails: (id: string | number) => `/admin/jobs/${id}`,
    applications: "/admin/applications",
    applicationDetails: (id: string | number) => `/admin/applications/${id}`,
    skills: "/admin/skills",
    tests: "/admin/tests",
    testsCreate: "/admin/tests/create",
    notifications: "/admin/notifications",
    reports: {
      root: "/admin/reports",
      overview: "/admin/reports/overview",
      applications: "/admin/reports/applications",
      jobs: "/admin/reports/jobs",
      cvParsing: "/admin/reports/cv-parsing",
    },
    auditLogs: "/admin/audit-logs",
    settings: "/admin/settings",
    help: "/admin/help",
  },
  employer: {
    login: "/employer/login",
    register: "/employer/register",
    forgotPassword: "/employer/forgot-password",
    resetPassword: "/employer/reset-password",
    root: "/employer",
    jobs: "/employer/jobs",
    createJob: "/employer/jobs/create",
    jobDetails: (id: string | number) => `/employer/jobs/${id}`,
    editJob: (id: string | number) => `/employer/jobs/${id}/edit`,
    jobApplicants: (id: string | number) => `/employer/jobs/${id}/applicants`,
    applicants: "/employer/applicants",
    applicantDetails: (id: string | number) => `/employer/applicants/${id}`,
    applicantTestDetails: (applicationId: string | number, assignmentId: string | number) =>
      `/employer/applicants/${applicationId}/tests/${assignmentId}`,
    interviews: "/employer/interviews",
    interviewDetails: (id: string | number) => `/employer/interviews/${id}`,
    tests: "/employer/tests",
    createTest: "/employer/tests/create",
    editTest: (id: string | number) => `/employer/tests/${id}/edit`,
    testDetails: (id: string | number) => `/employer/tests/${id}`,
    testAttemptGrading: (id: string | number, attemptId: string | number) =>
      `/employer/tests/${id}/attempts/${attemptId}/grading`,
    company: "/employer/company",
    profile: "/employer/profile",
    notifications: "/employer/notifications",
    settings: "/employer/settings",
  },
} as const)
